In [37]:
#simple numpy
import numpy as np
a = np.array([1,2])
b = np.array([3,4])
out = np.log(a)
print(out)
out = np.exp(a)
print(out)
#out = np.dot(a,b)
out = a.dot(b)
print(out)

[0.         0.69314718]
[2.71828183 7.3890561 ]
11


In [38]:
#magnitude of vector
out = np.linalg.norm(a)    #print magnitude of the vector
print(out)
out = np.linalg.norm(b)
print(out)
out = np.linalg.norm(np.dot(a,b))
print(out)

2.23606797749979
5.0
11.0


In [39]:
#vectors
angle_bw_two_vectors = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))     #cos(x) = dot product/(magnitude of both matrix)
print(angle_bw_two_vectors)
angle_in_radian = np.arccos(angle_bw_two_vectors) #print angle in radian
print(angle_in_radian)

0.9838699100999074
0.17985349979247847


In [40]:
# matrix
a = np.matrix([[1,2,3],[4,5,6]])
print(a)
print(a[0,1])  #print given index
x = np.array(a)
print(x)
print(x.T)     #transpose of a matrix
m = np.zeros((2,2))
print(m)
m = np.zeros((2,2,3))
print(m)
n = np.ones((3,5))
print(n)

z = np.random.random((3,3))
print(z)

[[1 2 3]
 [4 5 6]]
2
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.60531227 0.73884873 0.02037901]
 [0.30393388 0.0802311  0.68529807]
 [0.02561343 0.94943084 0.96419047]]


In [41]:
#statistical
h = np.random.randn(2,2)   #normal 
print(h)
print(h.mean())
print(h.var())

[[-0.80551635  1.69308042]
 [ 0.48466381  0.22538792]]
0.3994039511108295
0.7907456383636607


In [49]:
#inverse of matrix
p = np.array([[1,2],[3,4]])
q = np.array([[3,4],[5,6]])
inverse_of_p = np.linalg.inv(p)
print(inverse_of_p)

d = np.linalg.det(q)
print(d)
di = np.diag(p)
x = np.diag([1,2,3,4])
print(x)
x = np.trace(x)
print(x)

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000013
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
10
